### ISSUE TITLE
realtimecats.com doesn't work

### ISSUE THREAD

**Issue by roccomuso** [maxogden/websocket-stream#133]
The example on the homepage doesn't work. Probably for a `realtimecats.com` issue.
I've tested it successfully with `wss://echo.websocket.org`.

This the error:
```text
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (200)
    at ClientRequest._req.on (/tmp/asd/node_modules/ws/lib/WebSocket.js:656:26)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:473:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
```

**Comment by mcollina** [comment]
Ouch, would you mind sending a PR to fix it? Maybe pinging echo.websockets.org.

**Comment by maxogden** [comment]
It's a joke domain :D
