### ISSUE TITLE
Error event emits without error object

### ISSUE THREAD

**Issue by binarykitchen** [maxogden/websocket-stream#138]
In my videomail client code this strange thing sometimes happens: no error object is emited along with the error event.

Like

```js
stream.on('error', function (err) {
  console.log(err) // this will print undefined
})
```

Don't you agree, it should have an error object? An error without an error is not an error :)

**Comment by binarykitchen** [comment]
Btw in the stack trace I can see this happens when queue is drained and `Duplexify._destroy` is called.

**Comment by binarykitchen** [comment]
i am afraid, due to wrong configs, browserify sourcemaps are broken on production, hence this stack trace is kinda cryptic and not very useful:

```
Error
    at Function.VideomailError.create (https://videomail.io/js/main-1000576986.min.js:3:906305)
    at null.<anonymous> (https://videomail.io/js/main-1000576986.min.js:3:971808)
    at https://videomail.io/js/main-1000576986.min.js:3:735480
    at EventEmitter.emit (https://videomail.io/js/main-1000576986.min.js:3:735605)
    at Duplexify._destroy (https://videomail.io/js/main-1000576986.min.js:3:727187)
    at https://videomail.io/js/main-1000576986.min.js:3:727047
    at Item.run (https://videomail.io/js/main-1000576986.min.js:3:778418)
    at drainQueue (https://videomail.io/js/main-1000576986.min.js:3:777238)
    at arlong:beforeload:6:321
```

**Comment by mcollina** [comment]
Let us know if you can reproduce this reliably and/or have a better stacktrace.

**Comment by binarykitchen** [comment]
I'm afraid very hard to reproduce. Happens by random on a heavy traffic site.

Do you have a guess what this could be?

**Comment by mcollina** [comment]
Not really. Did it happen with the latest version of readable-stream? Can you try to roll that back?

**Comment by binarykitchen** [comment]
how? not using readable-stream anywhere in the videomail-client code

**Comment by mcollina** [comment]
Duplexify is relying on readable-stream internally.

**Comment by mcollina** [comment]
Did this happen after a very recent deploy? I released a new version a week ago.

**Comment by binarykitchen** [comment]
no, happened before as well

**Comment by mcollina** [comment]
then no, that's not the problem. We really need a stacktrace and/or a good way to reproduce.

**Comment by binarykitchen** [comment]
ugh, this will be difficult for me.

is there a useful tool/package to inspect/record a stream of all its events/data it had till the error was emitted?

**Comment by Juul** [comment]
As far as I can tell websocket-stream doesn't originate any errors itself but does propagate errors from the underlying WebSocket which of course is just a plain TCP socket, so your null errors could be either coming from the `ws` module or from the browser.

**Comment by binarykitchen** [comment]
@Juul @mcollina ok now i always can reproduce this. and it is on iphones only:

1. open www.videomail.io on safari
2. allow camera, initiate connection blahblah
3. hit the sleep button on your iphone
4. let it sleep for at least one min
5. unlock and it should reopen same site on safari
6. now you see that weird error

i expect websocket-stream to resume but not to throw an error. or at least throw a descriptive error.

**Comment by mcollina** [comment]
I think this is a safari-mobile specific bug. If you can get a stacktrace, we can definitely generate a new error if it's not provided by the platform.

**Comment by binarykitchen** [comment]
hard to get a stack trace here i am afraid - do you have any other examples running online producing valid stacktraces i could test from my iphone?

**Comment by mcollina** [comment]
You should be able to use Remote Web Inspector.

**Comment by binarykitchen** [comment]
good idea. turns out it is an event object, not an error object itself.

this screenshot tells more:
<img width="1253" alt="screen shot 2018-02-28 at 13 21 40" src="https://user-images.githubusercontent.com/177641/36762940-be4fbd30-1c8a-11e8-9f7d-51a94b7bac22.png">

when debugging deep down, looks like

```js
  function onerror(err) {
    stream.destroy(err)
  }
```

is the starting point. and funny is that `this` references to the global Window where `this.destroyed` is undefined. i expect it to be destroyed when iphone is locked/sleeping.

**Comment by mcollina** [comment]
@binarykitchen let us know if you can send a fix!

**Comment by binarykitchen** [comment]
dont know if i can.

`socket.onerror` <-- what instance is socket here in the browser?

its implementation has to be questioned here.

**Comment by mcollina** [comment]
it's a WebSocket

**Comment by binarykitchen** [comment]
native implementation?

**Comment by mcollina** [comment]
the WebSocket from the browser.

**Comment by binarykitchen** [comment]
okay, sounds like it's an ios bug of its websocket implementation ... where to start best?

**Comment by mcollina** [comment]
You should probably work around that in your code.

**Comment by binarykitchen** [comment]
already have but then, what if other non-ios browsers truly emit an error instead of an event during stream errors? then my app code gets complicated just because of ios weird websocket error handling?

**Comment by mcollina** [comment]
unfortunately yes.

**Comment by binarykitchen** [comment]
alright :(

... btw have reported to apple as well and will keep you posted here.
