### ISSUE TITLE
stream.push() after EOF

### ISSUE THREAD

**Issue by binarykitchen** [maxogden/websocket-stream#58]
I am seeing this in Google Chrome:

```
_stream_readable.js:168 Uncaught Error: stream.push() after EOF
_stream_readable.js:168 readableAddChunk
_stream_readable.js:149 Readable.push
_stream_transform.js:145 Transform.push
stream.js:73 onmessage
```

No idea what it means. It's a special case where I have closed the stream, yet this is happening. Possible to add more context in the error?

**Comment by mcollina** [comment]
Could you reproduce it reliably? May I ask you to add a test to [test-client](https://github.com/maxogden/websocket-stream/blob/master/test-client.js)?

It's a race condition (hurray!) between closing the Stream and closing the actual websocket. When you close the proxy, a `'close'` event is emitted, and [here](https://github.com/maxogden/websocket-stream/blob/master/stream.js#L35) the websocket is destroyed.

In the latest versions there were a bug in handling the errors (some errors were swallowed), and we changed the closing logic.

@mafintosh what do you think?

**Comment by binarykitchen** [comment]
Indeed, it's a race condition. Difficult to reproduce. Hence I recommend a stress test with 1000 random connections.

But you can see it yourself if you are lucky. Just open www.videomail.io on Google Chrome, expand the console under Developer tools, click on the logo (link to home) like crazy, 20 times afterwards. On each click a new websocket is generated and on every `beforeunload` window event the stream is ended. Sometimes inbetween these actions the above error occurs.

Furthermore I sometimes see this error on the server side

```
Error
Error: not opened
Stack
Error: not opened
at WebSocket.send (/var/www/videomail/production/source/node_modules/ws/lib/WebSocket.js:213:38)
at DestroyableTransform.socketWriteNode [as _transform] (/var/www/videomail/production/source/node_modules/websocket-stream/stream.js:38:12)
...
```

Both errors are somewhat related. But the latter one is more a `ws` issue I guess.

Anyway, I really think a random stress test would be the way to go ...

**Comment by mafintosh** [comment]
@binarykitchen could you add a code snippet that i can run to show this error?

**Comment by mcollina** [comment]
That error you see on the server side is perfectly fine. It should be emitted by the websocketstream object, and you should handle it properly. Before 1.2/1.3, either it was swallowed or it was thrown. If a connection is not closed properly and you try to send stuff, you will get that.

Yeah, a small script to reproduce will help us fixing this, otherwise is hunting in the dark.

**Comment by binarykitchen** [comment]
I am afraid no. But it happens almost every time I click on www.videomail.io's logo like crazy, 20 times over again. That's why I recommend random stress tests.

All I can tell is that it's happening in this code (I removed parts which aren't relevant):
https://gist.github.com/binarykitchen/63bfeb6cc50057c1af6f

Okay, how can I examine if a connection is closed properly before creating a new one?

**Comment by mcollina** [comment]
@binarykitchen you can write that random stress test.

**Comment by binarykitchen** [comment]
Yeah maybe later. Too busy looking for a job / project right now :(

**Comment by jnordberg** [comment]
I'm also seeing this in node (v5.1.1), don't know if it is the same cause but I can't seem to reproduce it locally. Only happens on my server when streaming multiple large files (using @maxogden's multiplex).

```
Error: stream.push() after EOF
    at readableAddChunk (node_modules/readable-stream/lib/_stream_readable.js:185:15)
    at DestroyableTransform.Readable.push (node_modules/readable-stream/lib/_stream_readable.js:163:10)
    at DestroyableTransform.Transform.push (node_modules/readable-stream/lib/_stream_transform.js:133:32)
    at WebSocket.onmessage (node_modules/websocket-stream/stream.js:75:11)
    at WebSocket.onMessage (node_modules/ws/lib/WebSocket.js:418:14)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onbinary (node_modules/ws/lib/WebSocket.js:823:10)
    at node_modules/ws/lib/Receiver.js:537:18
    at node_modules/ws/lib/Receiver.js:361:7
```

**Comment by mcollina** [comment]
Are you using [pump](http://npm.im/pump) to pipe your streams together?

**Comment by jnordberg** [comment]
I am now :) Looks like it solved my problems, thanks!

**Comment by JustinLiao1314** [comment]
I am also this problem at node V4.2.4 websocket-stream V2.0.2.
```bash
[2016-03-07 21:39:41.729] [ERROR] boot - s3.17238 - uncaughtException, process will exit. [Error: stream.push() after EOF]
Error: stream.push() after EOF
  at readableAddChunk (/root/daniujia_production_mqttServer_1.0.5/node_modules/mosca/node_modules/websocket-stream/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:168:15)
  at DestroyableTransform.Readable.push (/root/daniujia_production_mqttServer_1.0.5/node_modules/mosca/node_modules/websocket-stream/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/root/daniujia_production_mqttServer_1.0.5/node_modules/mosca/node_modules/websocket-stream/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at WebSocket.onmessage (/root/daniujia_production_mqttServer_1.0.5/node_modules/mosca/node_modules/websocket-stream/stream.js:75:11)
  at WebSocket.onMessage (/root/daniujia_production_mqttServer_1.0.5/node_modules/mosca/node_modules/websocket-stream/node_modules/ws/lib/WebSocket.js:418:14)
  at emitTwo (events.js:87:13)
  at WebSocket.emit (events.js:172:7)
  at Receiver.onbinary (/root/daniujia_production_mqttServer_1.0.5/node_modules/mosca/node_modules/websocket-stream/node_modules/ws/lib/WebSocket.js:823:10)
  at /root/daniujia_production_mqttServer_1.0.5/node_modules/mosca/node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:537:18
  at /root/daniujia_production_mqttServer_1.0.5/node_modules/mosca/node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:361:7
  at /root/daniujia_production_mqttServer_1.0.5/node_modules/mosca/node_modules/websocket-stream/node_modules/ws/lib/PerMessageDeflate.js:238:5
  at afterWrite (_stream_writable.js:346:3)
  at onwrite (_stream_writable.js:337:7)
  at WritableState.onwrite (_stream_writable.js:89:5)
  at afterTransform (_stream_transform.js:79:5)
  at TransformState.afterTransform (_stream_transform.js:54:12)
  at Zlib.callback (zlib.js:614:5)
```

**Comment by desaintmartin** [comment]
Hello,
Using pump is made for you only if you want to close your local stream when the websocket stream closes.
What if I don't want to close my local stream? Say I have a continous, singleton, stream (like video streaming) that I want to still continue after my last client disconnected? ;)

More seriously: 
I suspect websocket-stream to still try to send (in socketWriteNode) a packet even if the client disconnected just after requesting the data, resulting in this exception. For development, manually try-catching socket.send solves the problem, but being able to set a callback for that would be nice. What do you think?
